name: Main

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+.[0-9]+.rc[0-9]+'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    uses: adya/pack-skse-mod/.github/workflows/pack.yml@main
    with:
      CMAKE_PROJECT_DIR: "Main/Plugin"
      CMAKE_VR_CONFIG_PRESET: ''
      CMAKE_VR_BUILD_PRESET: ''
      FOMOD_INCLUDE_PDB: true
      FOMOD_MOD_NAME: "NPCs Names Distributor"
      FOMOD_MOD_AUTHOR: "sasnikol"
      FOMOD_MOD_NEXUS_ID: "73081"
      FOMOD_DEFAULT_IMAGE: "FOMOD/images/cover.png"
      PUBLISH_MOD_CHANGELOG_FILE: "FOMOD/changelog.txt"
      PUBLISH_MOD_DESCRIPTION_FILE: "FOMOD/description.txt"
